Refactor/income endpoints refactor
programacion-6/ExpenseTrackerGroup1 pull request #14
Opened 2024-09-27 01:35 UTC by EmanuelGalindoC

## What did I do?
- I fixed and updated Income's dtos with the latest update

## How did I do it ?
- Checking the last update about Dtos and Database implementation
- Creating and updating new classes and olders ones to the newest version

## Why did I do it ?
- It is necessary to check Income endpoints and continue to improving the app.

2024-09-27 03:45 UTC, DiegoFigueroaSevillano requested changes
We need to inject the new repositories and services.
Go to the ./configuration/config.cs file and enter the new repositories and services you created

2024-09-27 13:41 UTC, DiegoFigueroaSevillano requested changes
![imagen](https://github.com/user-attachments/assets/30a4167e-c1e3-4b8b-b3cd-a6ca6840d7b9)
In your Income entity file, you have several constructors, but we are no longer doing it this way, in the entities we only define the data that they may have, this will affect your Data.

La imagen en un ejemplo de como debe de estar, puedes ver los archivos user, goal y budget

2024-09-27 14:12 UTC, DiegoFigueroaSevillano requested changes
Tengo este error al ejecutar tus endpoints:

![imagen](https://github.com/user-attachments/assets/ab4df590-8ca9-4196-ab34-f9900a055dd8)


Esto es por el nombre de la tabla, en tu repositorio lo tienes como Incomes cuando es solo Income.
Cambia el nombre de la tabla en tu repositorio.

2024-09-27 14:12 UTC, DiegoFigueroaSevillano commented on ExpenseTracker/Dtos/IncomeDtos/CreateIncomeDto.cs
> +    }
Esta bien la logica, solo que con los cambios a la entidad Income esto va a tener un pequeño refactor.

Al final terminara siendo similar a esto:

![imagen](https://github.com/user-attachments/assets/9e9be118-fc92-4003-b9e9-705974fce46c)

2024-09-27 14:12 UTC, DiegoFigueroaSevillano commented on ExpenseTracker/Dtos/IncomeDtos/UpdateIncomeInDto.cs
> +        };
Esta bien la logica, pero igual, con los cambios a la entidad Income esto tendra pequeños cambios.

2024-09-27 14:12 UTC, DiegoFigueroaSevillano commented on ExpenseTracker/Interfaces/Repository/IIncomeRepository.cs
> -    IGetAllOperation<Income>
Sigue usando el getAll porfavor, en los requerimiento estaba esta funcion igual

2024-09-27 14:12 UTC, DiegoFigueroaSevillano commented on ExpenseTracker/Interfaces/Service/IIncomeService.cs
> +    public interface IIncomeService
De igual forma aqui faltaria el servicio de getAll

2024-09-27 14:19 UTC, DiegoFigueroaSevillano commented
![imagen](https://github.com/user-attachments/assets/d0ea0a19-4f1e-44d3-91b9-be359fe61dda)

Tengo este error en tus endpoint al momento de crear, pero es porque no le pasamos la columna ID desde el repositorio.

![imagen](https://github.com/user-attachments/assets/57a2a892-76c0-47c0-bda6-43a6df7ba32b)

Deberia estar asi el metodo create

2024-09-28 16:36 UTC, EmanuelGalindoC commented on ExpenseTracker/Dtos/IncomeDtos/UpdateIncomeInDto.cs
> +        };
Done

2024-09-28 20:45 UTC, DiegoFigueroaSevillano approved these changes

2024-09-28 20:45 UTC, merged